name: EJSON Action Example

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Encrypt file
      uses: Drafteame/ejson-action@feat/ejson-version-parameter
      id: encrypt
      with:
        action: encrypt
        file_path: '${{ github.workspace }}/encrypted/test.ejson'
        ejson_version: '1.4.1'

    - name: Encrypted content
      run: |
        echo "Encrypted content:"
        cat '${{ github.workspace }}/encrypted/test.ejson'

    - name: Decrypt file
      uses: Drafteame/ejson-action@feat/ejson-version-parameter
      id: decrypt
      with:
        action: decrypt
        file_path: '${{ github.workspace }}/encrypted/test.ejson'
        private_key: ${{ secrets.EJSON_PRIVATE_KEY }}
        out_file: ${{ github.workspace }}/decrypted/test.json
        ejson_version: '1.4.1'

    - name: Decrypted content
      run: |
        echo "Decrypted:"
        echo '${{ steps.decrypt.outputs.decrypted }}'
        echo
        echo

        echo "Stored File:"
        cat '${{ github.workspace }}/decrypted/test.json'
        echo "---------------End of File -------------"