name: EJSON Action Example

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Decrypt file
      uses: Drafteame/ejson-action@main
      id: decrypt
      with:
        action: decrypt
        file_path: ${{ github.workspace }}/dev.ejson
        private_key: ${{ secrets.EJSON_PRIVATE_KEY }}
        out_file: ${{ github.workspace }}/decrypted/dev.json

    - name: Decrypted content
      run: |
        echo "Decrypted:"
        echo '${{ steps.decrypt.outputs.decrypted }}'
        echo
        echo

        echo "Stored File:"
        cat '${{ github.workspace }}/decrypted/dev.json'
        echo "End of File"